### ISSUE TITLE
Add to README, permissions issue & fix

### ISSUE THREAD

**Issue by sulthan-ahmed** [Alex-Swann/acp-vpn-bash#2]
Super dooper script thanks.  Maybe it was my fault but I copied the script and it would display the following when I tried to run it:

`sudo: ./acp_vpn.sh: command not found`

so I had to the change the permission of the file 

`chmod 777 acp_vpn.sh`

it then worked a treat :)

**Comment by Alex-Swann** [comment]
I'll add this to the docs. It works for me without needing to do this, but Github doesn't allow committing chmod 777 to the file for some reason. so I'll add this note to the Readme for troubleshooting.

**Comment by sulthan-ahmed** [comment]
👍
